import React from "react";

export function UnitEconomicsCard() {
  return (
    <div
      style={{
        background: "rgba(10, 13, 24, 0.8)",
        border: "1px solid var(--bdr, rgba(255, 255, 255, 0.08))",
        borderRadius: "14px",
        padding: "24px",
        marginBottom: "28px",
        backdropFilter: "blur(14px)",
      }}
    >
      <div style={{ marginBottom: "20px" }}>
        <span
          style={{
            fontFamily: "var(--mono, monospace)",
            fontSize: "11px",
            fontWeight: 700,
            color: "var(--green, #22d3a0)",
            letterSpacing: "0.14em",
            textTransform: "uppercase",
            display: "block",
            marginBottom: "4px",
          }}
        >
          Sustainable Protocol Economics
        </span>
        <h3 style={{ fontSize: "20px", margin: "0 0 6px 0", color: "#ffffff", fontWeight: 700, letterSpacing: "-0.02em" }}>
          Unit Economics &amp; Break-Even Model
        </h3>
        <p style={{ fontSize: "13px", color: "var(--t2, #8d95b0)", margin: 0, lineHeight: "1.5" }}>
          QMA operates on real cashflow from day one. Ultra-low Arc gas fees and lightweight Python/FastAPI architecture allow the platform to achieve profitability at just 12 active trading bots.
        </p>
      </div>

      {/* 3 Revenue Streams Grid */}
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
          gap: "14px",
          marginBottom: "20px",
        }}
      >
        {/* Stream 1 */}
        <div
          style={{
            background: "rgba(255, 255, 255, 0.02)",
            border: "1px solid rgba(124, 111, 255, 0.2)",
            borderRadius: "10px",
            padding: "16px",
          }}
        >
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "8px" }}>
            <span style={{ fontSize: "12px", fontWeight: 700, color: "var(--accent, #7C6FFF)", fontFamily: "var(--sans, 'Inter', sans-serif)" }}>
              1. Marketplace Take-Rate
            </span>
            <span style={{ fontSize: "11px", background: "rgba(124, 111, 255, 0.15)", color: "var(--accent, #7C6FFF)", padding: "2px 6px", borderRadius: "4px", fontFamily: "var(--mono, monospace)" }}>
              10% – 15%
            </span>
          </div>
          <p style={{ fontSize: "12px", color: "var(--t2, #8d95b0)", lineHeight: "1.4", margin: "0 0 10px 0" }}>
            Deducted automatically on each x402 micropayment call. On a 0.02 USDC intelligence report, platform collects 0.002 USDC instantly.
          </p>
          <div style={{ fontSize: "11px", fontFamily: "var(--mono, monospace)", color: "#cbd5e1", background: "rgba(0, 0, 0, 0.35)", padding: "6px 8px", borderRadius: "6px" }}>
            100 Bots @ 200 queries/day &rarr; $1,200 – $1,800/mo
          </div>
        </div>

        {/* Stream 2 */}
        <div
          style={{
            background: "rgba(255, 255, 255, 0.02)",
            border: "1px solid rgba(245, 158, 11, 0.25)",
            borderRadius: "10px",
            padding: "16px",
          }}
        >
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "8px" }}>
            <span style={{ fontSize: "12px", fontWeight: 700, color: "var(--amber, #f59e0b)", fontFamily: "var(--sans, 'Inter', sans-serif)" }}>
              2. Treasury Yield Spread
            </span>
            <span style={{ fontSize: "11px", background: "rgba(245, 158, 11, 0.15)", color: "var(--amber, #f59e0b)", padding: "2px 6px", borderRadius: "4px", fontFamily: "var(--mono, monospace)" }}>
              10% of Yield
            </span>
          </div>
          <p style={{ fontSize: "12px", color: "var(--t2, #8d95b0)", lineHeight: "1.4", margin: "0 0 10px 0" }}>
            Platform retains 10% on gross interest generated by idle agent capital swept into Morpho vaults via Arc Earn Kit.
          </p>
          <div style={{ fontSize: "11px", fontFamily: "var(--mono, monospace)", color: "#cbd5e1", background: "rgba(0, 0, 0, 0.35)", padding: "6px 8px", borderRadius: "6px" }}>
            (Illustrative Scenario): $500K AUM @ 7.0% APY &rarr; $3,500/year net yield fee
          </div>
        </div>

        {/* Stream 3 */}
        <div
          style={{
            background: "rgba(255, 255, 255, 0.02)",
            border: "1px solid rgba(167, 139, 250, 0.25)",
            borderRadius: "10px",
            padding: "16px",
          }}
        >
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "8px" }}>
            <span style={{ fontSize: "12px", fontWeight: 700, color: "var(--purple, #a78bfa)", fontFamily: "var(--sans, 'Inter', sans-serif)" }}>
              3. Creator Staking &amp; Slashing
            </span>
            <span style={{ fontSize: "11px", background: "rgba(167, 139, 250, 0.15)", color: "var(--purple, #a78bfa)", padding: "2px 6px", borderRadius: "4px", fontFamily: "var(--mono, monospace)" }}>
              50 – 100 USDC Bond
            </span>
          </div>
          <p style={{ fontSize: "12px", color: "var(--t2, #8d95b0)", lineHeight: "1.4", margin: "0 0 10px 0" }}>
            Providers stake SLA collateral. If GenLayer validators detect fraudulent/spoofed reports, 50% refunds buyers and 50% enters Platform Reserve.
          </p>
          <div style={{ fontSize: "11px", fontFamily: "var(--mono, monospace)", color: "#cbd5e1", background: "rgba(0, 0, 0, 0.35)", padding: "6px 8px", borderRadius: "6px" }}>
            SLA Enforced by Settlement Contract &amp; Zero Platform Solvency Risk
          </div>
        </div>
      </div>

      {/* Break-Even Equation Box */}
      <div
        style={{
          background: "linear-gradient(135deg, rgba(34, 211, 160, 0.08) 0%, rgba(124, 111, 255, 0.08) 100%)",
          border: "1px solid rgba(34, 211, 160, 0.25)",
          borderRadius: "10px",
          padding: "16px 20px",
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          flexWrap: "wrap",
          gap: "16px",
        }}
      >
        <div>
          <strong style={{ fontSize: "14px", color: "#ffffff", display: "block", marginBottom: "2px", fontWeight: 600 }}>
            Break-Even Threshold: 12 – 15 Active Autonomous Bots
          </strong>
          <span style={{ fontSize: "12px", color: "var(--t2, #8d95b0)" }}>
            Infra OPEX: $35/mo · Arc Native Gas: $0.00002/tx · 85%+ Gross Contribution Margin.
          </span>
        </div>
        <div style={{ display: "flex", gap: "16px" }}>
          <div style={{ textAlign: "right" }}>
            <span style={{ fontSize: "10px", color: "var(--t3, #4a5270)", textTransform: "uppercase", display: "block", fontFamily: "var(--mono, monospace)" }}>Monthly OPEX</span>
            <strong style={{ fontSize: "14px", color: "var(--red, #f4475b)", fontFamily: "var(--mono, monospace)" }}>~$35 USD</strong>
          </div>
          <div style={{ textAlign: "right" }}>
            <span style={{ fontSize: "10px", color: "var(--t3, #4a5270)", textTransform: "uppercase", display: "block", fontFamily: "var(--mono, monospace)" }}>Break-Even Volume</span>
            <strong style={{ fontSize: "14px", color: "var(--green, #22d3a0)", fontFamily: "var(--mono, monospace)" }}>12 Bots</strong>
          </div>
          <div style={{ textAlign: "right" }}>
            <span style={{ fontSize: "10px", color: "var(--t3, #4a5270)", textTransform: "uppercase", display: "block", fontFamily: "var(--mono, monospace)" }}>Gas per query</span>
            <strong style={{ fontSize: "14px", color: "var(--accent, #7C6FFF)", fontFamily: "var(--mono, monospace)" }}>$0.00002</strong>
          </div>
        </div>
      </div>
    </div>
  );
}
