import React from "react";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/Card";
import { Badge } from "@/components/Badge";

export function UnitEconomicsCard() {
  return (
    <Card className="mb-8 rounded-2xl border-bdr bg-surface-1/90 backdrop-blur-md shadow-card overflow-hidden">
      <CardHeader className="p-6 sm:p-7 pb-4 sm:pb-5 border-b-0">
        <div className="flex items-center gap-2 mb-1.5">
          <span className="w-1.5 h-1.5 rounded-full bg-success shadow-[0_0_8px_var(--green)]" />
          <span className="font-mono text-[11px] font-bold text-success tracking-[0.14em] uppercase block">
            Sustainable Protocol Economics
          </span>
        </div>
        <CardTitle className="text-xl sm:text-2xl font-bold text-t1 tracking-tight">
          Unit Economics &amp; Break-Even Model
        </CardTitle>
        <CardDescription className="text-xs sm:text-sm text-t2 leading-relaxed max-w-3xl mt-1">
          QMA operates on real cashflow from day one. Ultra-low Arc gas fees and lightweight Python/FastAPI architecture allow the platform to achieve profitability at just 12 active trading bots.
        </CardDescription>
      </CardHeader>

      <CardContent className="p-6 sm:p-7 pt-0 sm:pt-0">
        {/* 3 Revenue Streams Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-5">
          {/* Stream 1 */}
          <div className="bg-surface-2/80 hover:bg-surface-2 border border-accent/25 hover:border-accent/45 rounded-xl p-4 sm:p-5 flex flex-col justify-between transition-colors shadow-sm">
            <div>
              <div className="flex justify-between items-center gap-2 mb-2.5">
                <span className="text-xs font-bold text-accent font-sans">
                  1. Marketplace Take-Rate
                </span>
                <Badge variant="dim" size="sm">
                  10% – 15%
                </Badge>
              </div>
              <p className="text-xs text-t2 leading-relaxed mb-4">
                Deducted automatically on each x402 micropayment call. On a 0.02 USDC intelligence report, platform collects 0.002 USDC instantly.
              </p>
            </div>
            <div className="text-[11px] font-mono text-t2 bg-surface-1/90 border border-bdr/60 px-3 py-2 rounded-lg flex items-center justify-between">
              <span>100 Bots @ 200 q/day</span>
              <span className="text-t1 font-semibold">&rarr; $1,200 – $1,800/mo</span>
            </div>
          </div>

          {/* Stream 2 */}
          <div className="bg-surface-2/80 hover:bg-surface-2 border border-warning/25 hover:border-warning/45 rounded-xl p-4 sm:p-5 flex flex-col justify-between transition-colors shadow-sm">
            <div>
              <div className="flex justify-between items-center gap-2 mb-2.5">
                <span className="text-xs font-bold text-warning font-sans">
                  2. Treasury Yield Spread
                </span>
                <Badge variant="warning" size="sm">
                  10% of Yield
                </Badge>
              </div>
              <p className="text-xs text-t2 leading-relaxed mb-4">
                Platform retains 10% on gross interest generated by idle agent capital swept into Morpho vaults via Arc Earn Kit.
              </p>
            </div>
            <div className="text-[11px] font-mono text-t2 bg-surface-1/90 border border-bdr/60 px-3 py-2 rounded-lg flex items-center justify-between">
              <span>$500K AUM @ 7% APY</span>
              <span className="text-warning font-semibold">&rarr; $3,500/yr fee</span>
            </div>
          </div>

          {/* Stream 3 */}
          <div className="bg-surface-2/80 hover:bg-surface-2 border border-purple-500/25 hover:border-purple-500/45 rounded-xl p-4 sm:p-5 flex flex-col justify-between transition-colors shadow-sm">
            <div>
              <div className="flex justify-between items-center gap-2 mb-2.5">
                <span className="text-xs font-bold text-[var(--purple,#a78bfa)] font-sans">
                  3. Creator Staking &amp; Slashing
                </span>
                <Badge variant="purple" size="sm">
                  50 – 100 USDC Bond
                </Badge>
              </div>
              <p className="text-xs text-t2 leading-relaxed mb-4">
                Providers stake SLA collateral. If GenLayer validators detect fraudulent/spoofed reports, 50% refunds buyers and 50% enters Platform Reserve.
              </p>
            </div>
            <div className="text-[11px] font-mono text-t2 bg-surface-1/90 border border-bdr/60 px-3 py-2 rounded-lg flex items-center justify-between">
              <span className="text-t2">SLA Enforced by</span>
              <span className="text-[var(--purple,#a78bfa)] font-semibold">Settlement Contract</span>
            </div>
          </div>
        </div>

        {/* Break-Even Equation Box */}
        <div className="bg-gradient-to-r from-success/10 via-surface-2/50 to-accent/10 border border-success/30 rounded-xl p-4 sm:p-5 flex flex-col lg:flex-row justify-between items-start lg:items-center gap-4 sm:gap-6 shadow-sm">
          <div className="space-y-1 max-w-xl">
            <div className="flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-success animate-pulse" />
              <strong className="text-sm sm:text-base font-semibold text-t1 tracking-tight">
                Break-Even Threshold: 12 – 15 Active Autonomous Bots
              </strong>
            </div>
            <p className="text-xs text-t2 leading-relaxed">
              Infra OPEX: $35/mo · Arc Native Gas: $0.00002/tx · 85%+ Gross Contribution Margin.
            </p>
          </div>
          <div className="flex flex-wrap sm:flex-nowrap gap-5 sm:gap-6 items-center w-full lg:w-auto pt-3 lg:pt-0 border-t border-bdr/40 lg:border-t-0">
            <div className="text-left sm:text-right">
              <span className="text-[10px] text-t3 uppercase block font-mono tracking-wider mb-0.5">Monthly OPEX</span>
              <strong className="text-sm sm:text-base text-danger font-mono font-bold tabular-nums">~$35 USD</strong>
            </div>
            <div className="h-8 w-px bg-bdr/60 hidden sm:block" />
            <div className="text-left sm:text-right">
              <span className="text-[10px] text-t3 uppercase block font-mono tracking-wider mb-0.5">Break-Even Volume</span>
              <strong className="text-sm sm:text-base text-success font-mono font-bold tabular-nums">12 Bots</strong>
            </div>
            <div className="h-8 w-px bg-bdr/60 hidden sm:block" />
            <div className="text-left sm:text-right">
              <span className="text-[10px] text-t3 uppercase block font-mono tracking-wider mb-0.5">Gas per query</span>
              <strong className="text-sm sm:text-base text-accent font-mono font-bold tabular-nums">$0.00002</strong>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

export default UnitEconomicsCard;
