import React from "react";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/Card";
import { Badge } from "@/components/Badge";

export function UnitEconomicsCard() {
  return (
    <Card className="mb-7 bg-bg-1/80 border-bdr p-0 overflow-hidden">
      <CardHeader className="p-6 pb-4 border-b-0">
        <span className="font-mono text-[11px] font-bold text-qmaGreen tracking-[0.14em] uppercase block mb-1">
          Sustainable Protocol Economics
        </span>
        <CardTitle className="text-xl font-bold text-white tracking-tight">
          Unit Economics &amp; Break-Even Model
        </CardTitle>
        <CardDescription className="text-xs text-t2 leading-relaxed">
          QMA operates on real cashflow from day one. Ultra-low Arc gas fees and lightweight Python/FastAPI architecture allow the platform to achieve profitability at just 12 active trading bots.
        </CardDescription>
      </CardHeader>

      <CardContent className="p-6 pt-0">
        {/* 3 Revenue Streams Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3.5 mb-5">
          {/* Stream 1 */}
          <div className="bg-white/[0.02] border border-accent/20 rounded-lg p-4 flex flex-col justify-between">
            <div>
              <div className="flex justify-between items-center mb-2">
                <span className="text-xs font-bold text-accent font-sans">
                  1. Marketplace Take-Rate
                </span>
                <Badge variant="dim" size="sm">
                  10% – 15%
                </Badge>
              </div>
              <p className="text-xs text-t2 leading-snug mb-3">
                Deducted automatically on each x402 micropayment call. On a 0.02 USDC intelligence report, platform collects 0.002 USDC instantly.
              </p>
            </div>
            <div className="text-[11px] font-mono text-slate-300 bg-black/35 px-2.5 py-1.5 rounded-md">
              100 Bots @ 200 queries/day &rarr; $1,200 – $1,800/mo
            </div>
          </div>

          {/* Stream 2 */}
          <div className="bg-white/[0.02] border border-amber-500/25 rounded-lg p-4 flex flex-col justify-between">
            <div>
              <div className="flex justify-between items-center mb-2">
                <span className="text-xs font-bold text-qmaAmber font-sans">
                  2. Treasury Yield Spread
                </span>
                <Badge variant="warning" size="sm">
                  10% of Yield
                </Badge>
              </div>
              <p className="text-xs text-t2 leading-snug mb-3">
                Platform retains 10% on gross interest generated by idle agent capital swept into Morpho vaults via Arc Earn Kit.
              </p>
            </div>
            <div className="text-[11px] font-mono text-slate-300 bg-black/35 px-2.5 py-1.5 rounded-md">
              $500K AUM @ 7.0% APY &rarr; $3,500/yr net fee
            </div>
          </div>

          {/* Stream 3 */}
          <div className="bg-white/[0.02] border border-purple-500/25 rounded-lg p-4 flex flex-col justify-between">
            <div>
              <div className="flex justify-between items-center mb-2">
                <span className="text-xs font-bold text-qmaPurple font-sans">
                  3. Creator Staking &amp; Slashing
                </span>
                <Badge variant="purple" size="sm">
                  50 – 100 USDC Bond
                </Badge>
              </div>
              <p className="text-xs text-t2 leading-snug mb-3">
                Providers stake SLA collateral. If GenLayer validators detect fraudulent/spoofed reports, 50% refunds buyers and 50% enters Platform Reserve.
              </p>
            </div>
            <div className="text-[11px] font-mono text-slate-300 bg-black/35 px-2.5 py-1.5 rounded-md">
              SLA Enforced by Settlement Contract
            </div>
          </div>
        </div>

        {/* Break-Even Equation Box */}
        <div className="bg-gradient-to-r from-qmaGreen/10 to-accent/10 border border-qmaGreen/25 rounded-lg p-4 sm:p-5 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
          <div>
            <strong className="text-sm font-semibold text-white block mb-0.5">
              Break-Even Threshold: 12 – 15 Active Autonomous Bots
            </strong>
            <span className="text-xs text-t2">
              Infra OPEX: $35/mo · Arc Native Gas: $0.00002/tx · 85%+ Gross Contribution Margin.
            </span>
          </div>
          <div className="flex gap-4 self-end sm:self-center">
            <div className="text-right">
              <span className="text-[10px] text-t3 uppercase block font-mono">Monthly OPEX</span>
              <strong className="text-sm text-qmaRed font-mono">~$35 USD</strong>
            </div>
            <div className="text-right">
              <span className="text-[10px] text-t3 uppercase block font-mono">Break-Even Volume</span>
              <strong className="text-sm text-qmaGreen font-mono">12 Bots</strong>
            </div>
            <div className="text-right">
              <span className="text-[10px] text-t3 uppercase block font-mono">Gas per query</span>
              <strong className="text-sm text-accent font-mono">$0.00002</strong>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

export default UnitEconomicsCard;
