"""OpenAPI security schemes used by the QMA HTTP boundary.

All schemes are non-raising extractors. Endpoint business logic remains the
source of truth for whether a token is required, including its existing error
messages and query-parameter fallbacks.
"""

from fastapi.security import APIKeyHeader


qma_access_token_header = APIKeyHeader(
    name="X-QMA-Access-Token",
    scheme_name="X-QMA-Access-Token",
    auto_error=False,
    description="""Short-lived JWT granted after a successful invoice settlement. Used to unlock paid report endpoints.

**Retrieval:** A token can be returned by payment verification/status after the invoice reaches the server-accepted paid state.
**Enforcement:** Required on paid report endpoints and `POST /api/v1/chat` via the `X-QMA-Access-Token` header. Missing, invalid, expired, or invoice-mismatched tokens trigger `403 Forbidden`.""",
)

qma_wallet_token_header = APIKeyHeader(
    name="X-QMA-Wallet-Token",
    scheme_name="X-QMA-Wallet-Token",
    auto_error=False,
    description="""Wallet profile session JWT, generated by signing a SIWE-like message proving wallet ownership.

**Retrieval:** Returned by the `/api/v1/wallets/{address}/session` endpoint.
**Optional vs Required:**
- **Required:** private report retrieval and wallet-owner Agent Session operations.
- **Owner or worker:** `GET/PATCH /api/v1/sessions/{session_id}` accepts either this owner token or the internal worker secret.
- **Optional:** wallet payments, legacy wallet metrics, and wallet entitlements return redacted public data when the token is absent. A supplied but invalid token is rejected.
- **Not used:** wallet summary and its deprecated alias are public.""",
)

qma_admin_token_header = APIKeyHeader(
    name="x-qma-admin-token",
    scheme_name="x-qma-admin-token",
    auto_error=False,
    description="""Static administrative token for platform operations.

**Enforcement:**
- **Required:** `POST /api/v1/providers/{provider_id}/toggle` and `POST /api/v1/creators/applications/{application_id}/review`.
- **Required for an unfiltered application list:** `GET /api/v1/creators/applications` accepts an admin token to list all applications; without it, callers must provide a wallet filter.
- **Conditional:** provider discovery/stats require the token only when `include_disabled=true`.
Invalid or missing credentials on a protected admin operation return `403 Forbidden`.""",
)

qma_internal_secret_header = APIKeyHeader(
    name="x-qma-internal-secret",
    scheme_name="x-qma-internal-secret",
    auto_error=False,
    description="""Server-to-server secret for trusted QMA workers and the Arc Gateway.

It authenticates Agent Session queue/event/runtime operations. It must never be embedded in frontend code, browser storage, examples, logs, or public client configuration. Gateway-only `/api/internal/*` routes are excluded from public OpenAPI entirely.""",
)

qma_invoice_secret_header = APIKeyHeader(
    name="X-QMA-Invoice-Secret",
    scheme_name="X-QMA-Invoice-Secret",
    auto_error=False,
    description="""Invoice secret used to prove ownership/buyer binding for an invoice status check.

**Fallback:** Can be passed via the `invoice_secret` query parameter for backward compatibility.
The secret is scoped to one invoice and is not a wallet, admin, paid-report, or worker credential.""",
)
